select OrderType 
     , OrderNbr 
     , LineNbr 
     , OrderDate 
     , DeletedDatetime 
     , DeletedBy 
     , InventoryID 
     , SubItemID 
     , SiteID 
     , LocationID 
     , OrderQty 
     , ShippedQty 
     , UnitPrice 
     , UnitCost 
     , ExtPrice 
     , ExtCost 
     , DiscPct 
     , DiscAmt 
     , ManualDisc 
     , ReasonCode 
     , OpenQty 
     , OpenAmt 
     , LineAmt 
     , Completed 
     , OrigOrderType 
     , OrigOrderNbr 
     , OrigLineNbr 
     , OrigShipmentType 
     , OpenLine 
     , BilledQty 
     , UnbilledQty 
     , UnbilledAmt 
     , ShipDate 
     , CancelDate 
     , BilledAmt 
     , DiscountID 
     , DiscountSequenceID 
     , InvoiceType 
     , InvoiceNbr 
     , InvoiceLineNbr 
     , InvoiceDate 
     , IsFree 
     , POCreate 
     , POCreated 
     , POSource 
     , POSiteID 
     , QtyOnOrders 
     , CustomerOrderNbr 
     , POCreateDate 
     , IsStockItem 
     , NetSales 
     , MarginAmt 
     , MarginPct 
     , CreatedDatetime 
     , CreatedBy 
from SOLineDetetions
-- where DeletedDatetime >= dateadd(hour, -2, getdate())