import os
from dotenv import load_dotenv

load_dotenv()


TABLES = {
    'rmi_Receipts':{
        'keys': ['RMANumber', 'ReceiptID', 'RMAID', 'RMALineID'],
        'columns': [
            'RMANumber',
            'ReceiptDate',
            'ReceiptID',
            'RMAID',
            'RMALineID',
            'Qty',
            'InventoryCD',
            'Location',
            'ItemType',
            'ItemCategory',
            'Descr',
            'Price',
            'Cost'
        ],
        'update_columns':['ReceiptDate', 'Qty', 'InventoryCD', 'Location', 'ItemType', 'ItemCategory', 'Descr', 'Price', 'Cost']
    },    
    'rmi_ClosedShipments':{
        'keys': ['RMANumber', 'RMAID', 'RMALineID', 'RMAType'],
        'columns': [
            'RMANumber',
            'RMAID',
            'RMALineID',
            'RMAType',
            'CreateDate',
            'ShipDate',
            'InventoryCD',
            'QtyShipped',
            'QtyToShip',
            'Location',
            'ItemCategory',
            'Descr',
            'Carrier',
            'CarrierCode',
            'Priority',
            'Tracking',
            'FreightCost',
            'OutboundShipMethod'
        ],
        'update_columns':[
            'CreateDate',
            'ShipDate',
            'InventoryCD',
            'QtyShipped',
            'QtyToShip',
            'Location',
            'ItemCategory',
            'Descr',
            'Carrier',
            'CarrierCode',
            'Priority',
            'Tracking',
            'FreightCost',
            'OutboundShipMethod'
        ]
    }, 
    'rmi_RMAStatus':{
        'keys': ['RMANumber', 'RMAID', 'RMALineID', 'RMAType'],
        'columns': [
            'RMANumber',
            'RMAID',
            'RMALineID',
            'RMAType',
            'RMAStatus',
            'CustomerRef',
            'RMALineNbr',
            'LineStatus',
            'InventoryCD',
            'Qty',
            'Descr',
            'RMATypeName',
            'CreateDate',
            'RMILastModifiedDate',
            'LastChecked',
            'Carrier',
            'Priority'
        ],
        'update_columns':[
            'RMAStatus',
            'CustomerRef',
            'RMALineNbr',
            'LineStatus',
            'InventoryCD',
            'Qty',
            'Descr',
            'RMATypeName',
            'CreateDate',
            'RMILastModifiedDate',
            'LastChecked',
            'Carrier',
            'Priority'
        ]
    }, 
    'RedstagInventorySummary':{
        'keys': ['InventoryCD',],
        'columns': [
            'InventoryCD',
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ],
        'update_columns':[
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ]
    },
    'RedstagInventoryDetail':{
        'keys': ['InventoryCD', 'Warehouse'],
        'columns': [
            'InventoryCD',
            'Warehouse',
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ],
        'update_columns':[
            'Expected',
            'Processed',
            'PutAway',
            'Available',
            'Allocated',
            'Reserved',
            'Picked',
            'Advertised',
            'OnHand',
            'Timestamp',
        ]
    },
    '_util.acu_api_log':{
        'keys': [
            'Entity',
            'KeyValue',
            'Operation',
            'Timestamp'
        ],
        'columns': [
            'Entity',
            'KeyValue',
            'Operation',
            'Payload',
            'Response',
            'Timestamp'
        ],
        'update_columns':[
            'Payload',
            'Response',
        ]
    },
    '_util.SOOrderDeletions':{
        'keys': ['OrderType', 'OrderNbr'],
        'columns': [
            'OrderType',
            'OrderNbr',
            'DeletedBy',
            'DeletedDatetime'
        ],
        'update_columns':[
            'DeletedBy',
            'DeletedDatetime'
        ]
    },
    '_util.SOLineDeletions':{
        'keys': ['OrderType', 'OrderNbr', 'LineNbr'],
        'columns': [
            'OrderType',
            'OrderNbr',
            'LineNbr',
            'OrderDate',
            'DeletedDatetime',
            'DeletedBy',
            'InventoryID',
            'SubItemID',
            'SiteID',
            'LocationID',
            'OrderQty',
            'ShippedQty',
            'UnitPrice',
            'UnitCost',
            'ExtPrice',
            'ExtCost',
            'DiscPct',
            'DiscAmt',
            'ManualDisc',
            'ReasonCode',
            'OpenQty',
            'OpenAmt',
            'LineAmt',
            'Completed',
            'OrigOrderType',
            'OrigOrderNbr',
            'OrigLineNbr',
            'OrigShipmentType',
            'OpenLine',
            'BilledQty',
            'UnbilledQty',
            'UnbilledAmt',
            'ShipDate',
            'CancelDate',
            'BilledAmt',
            'DiscountID',
            'DiscountSequenceID',
            'InvoiceType',
            'InvoiceNbr',
            'InvoiceLineNbr',
            'InvoiceDate',
            'IsFree',
            'POCreate',
            'POCreated',
            'POSource',
            'POSiteID',
            'QtyOnOrders',
            'CustomerOrderNbr',
            'POCreateDate',
            'IsStockItem',
            'NetSales',
            'MarginAmt',
            'MarginPct',
            'CreatedDatetime',
            'CreatedBy',
        ],
        'update_columns':[
            'OrderDate',
            'DeletedDatetime',
            'DeletedBy',
            'InventoryID',
            'SubItemID',
            'SiteID',
            'LocationID',
            'OrderQty',
            'ShippedQty',
            'UnitPrice',
            'UnitCost',
            'ExtPrice',
            'ExtCost',
            'DiscPct',
            'DiscAmt',
            'ManualDisc',
            'ReasonCode',
            'OpenQty',
            'OpenAmt',
            'LineAmt',
            'Completed',
            'OrigOrderType',
            'OrigOrderNbr',
            'OrigLineNbr',
            'OrigShipmentType',
            'OpenLine',
            'BilledQty',
            'UnbilledQty',
            'UnbilledAmt',
            'ShipDate',
            'CancelDate',
            'BilledAmt',
            'DiscountID',
            'DiscountSequenceID',
            'InvoiceType',
            'InvoiceNbr',
            'InvoiceLineNbr',
            'InvoiceDate',
            'IsFree',
            'POCreate',
            'POCreated',
            'POSource',
            'POSiteID',
            'QtyOnOrders',
            'CustomerOrderNbr',
            'POCreateDate',
            'IsStockItem',
            'NetSales',
            'MarginAmt',
            'MarginPct',
            'CreatedDatetime',
            'CreatedBy',
        ]
    },
    '_util.SOShipmentDeletions':{
        'keys': ['ShipmentNbr'],
        'columns': [
            'ShipmentNbr',
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ],
        'update_columns':[
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ]
    },
    '_util.SOOrderShipmentDeletions':{
        'keys': ['OrderType', 'OrderNbr', 'ShipmentNbr'],
        'columns': [
            'OrderType',
            'OrderNbr',
            'ShipmentNbr',
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ],
        'update_columns':[
            'ShipDate',
            'DeletedBy',
            'DeletedDatetime'
        ]
    },
    'AdDetails': {
        'keys': [
            'AdCode',
        ],
        'columns': [
            'AdCode',
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
        'update_columns': [
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
    },
    'criteo.campaign_performance_daily': {
        'keys': [
            'report_date',
            'campaign_id'
        ],
        'columns': [
            'report_date',
            'advertiser_id',
            'campaign_id',
            'campaign_name',
            'impressions',
            'clicks',
            'cost',
            'conversions',
            'revenue',
            'load_timestamp',

        ],
        'update_columns': [
            'advertiser_id',
            'campaign_name',
            'impressions',
            'clicks',
            'cost',
            'conversions',
            'revenue',
            'load_timestamp',
        ],
    },
    'criteo.diff_log': {
        'keys': [
            'report_date',
            'campaign_id',
            'last_ts'
        ],
        'columns': [
            'report_date',
            'campaign_id',
            'last_ts',
            'current_ts',
            'impr_current',
            'impr_last',
            'clicks_current',
            'clicks_last',
            'cost_current',
            'cost_last',
            'revenue_current',
            'revenue_last',
            'diff'
        ],
        'update_columns': [
            'current_ts',
            'impr_current',
            'impr_last',
            'clicks_current',
            'clicks_last',
            'cost_current',
            'cost_last',
            'convr_current',
            'convr_last',
            'revenue_current',
            'revenue_last',
            'diff'
        ],
    },
    'acu.Quotes': {
        'keys': [
            'OrderType',
            'QuoteNbr',
            'LineNbr',
        ],
        'columns': [
            'OrderType',
            'QuoteNbr',
            'LineNbr',
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'LastModifiedDT',
            'CreatedDT',
            'AttachedOrderType',
            'AttachedOrderNbr',
            'LastChecked'
        ],
        'update_columns': [
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'LastModifiedDT',
            'CreatedDT',
            'AttachedOrderType',
            'AttachedOrderNbr',
            'LastChecked'
        ],
    },
    'acu.SalesOrders': {
        'keys': [
            'OrderType',
            'OrderNumber',
            'LineNbr',
        ],
        'columns': [
            'OrderType',
            'OrderNumber',
            'LineNbr',
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'LastModifiedDT',
            'DiscountCode',
            'DiscountAmt',
            'LineCost',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'ShipDate',
            'ShipmentNbr',
            'ShipStatus',
            'ShipmentWH',
            'Completed',
            'OriginalOrderType',
            'OriginalOrderNbr',
            'FreightPrice',
            'PremiumFreightPrice',
            'FreightTotal',
            'CreatedDT',
            'CreatedBy',
            'LastModifiedBy',
            'LastChecked'
        ],
        'update_columns': [
            'DatePlaced',
            'CustomerID',
            'CustomerName',
            'CustomerClass',
            'InventoryCD',
            'Description',
            'Quantity',
            'LinePrice',
            'OrderTotal',
            'Status',
            'CustOrderNumber',
            'D2CSalesperson',
            'SalespersonName',
            'SalespersonEmail',
            'B2BSalesperson',
            'LastModifiedDT',
            'DiscountCode',
            'Phone',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Zip',
            'Country',
            'LineAmount',
            'ReplenishmentClass',
            'StockItem',
            'OrderLineWH',
            'ShipDate',
            'ShipmentNbr',
            'ShipStatus',
            'ShipmentWH',
            'Completed',
            'OriginalOrderType',
            'OriginalOrderNbr',
            'FreightPrice',
            'PremiumFreightPrice',
            'FreightTotal',
            'CreatedDT',
            'CreatedBy',
            'LastModifiedBy',
            'LastChecked'
        ],
    },
    #     'json.K_OrderIngest': {
    #     'keys': [
    #         'OrderNbr',
    #         'AcuStatus',
    #     ],
    #     'columns': [
    #         'OrderNbr',
    #         'jsonData',
    #         'AcuStatus',
    #         'DatetimeSent',
    #         'ResponseText',
    #     ],
    #     'update_columns': [
    #         'jsonData',
    #         'DatetimeSent',
    #         'ResponseText',
    #     ],
    # },
    'K_OrderIngest': {
        'keys': [
            'OrderNbr',
            'Status',
        ],
        'columns': [
            'OrderNbr',
            'jsonData',
            'AcuStatus',
            'DatetimeSent',
            'ResponseText',
            'Status',
            'LastChecked',
        ],
        'update_columns': [
            'jsonData',
            'DatetimeSent',
            'ResponseText',
            'LastChecked',
        ],
    },
    'acu.Shipments': {
        'keys': [
            'ShipmentNbr',
            'ShipLineNbr',
            'OrderNbr',
            'OrderLineNbr',
        ],
        'columns': [
            'ShipmentNbr',
            'ShipLineNbr',
            'Status',
            'OrderNbr',
            'OrderLineNbr',
            'OrderDate',
            'InventoryCD',
            'OrderQTY',
            'ShipQTY',
            'ShipDate',
            'CustomerID',
            'AccountName',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Country',
            'Zip',
            'WarehouseID',
            'PackageCount',
            'SOLinePrice',
            'FreightCost',
            'SenttoWH',
            'InsertedDT',
            'LastModifiedDT',
            'Tracking',
            'TrackingCreatedDate',
            'CustomerPhone',
            'Attention',
            'ShipVia',
            'Carrier',
            'CourierCode',
            'CourierName',
            'ConfirmedDateTime',
            'CreatedDatetime',
        ],
        'update_columns': [
            'Status',
            'OrderDate',
            'InventoryCD',
            'OrderQTY',
            'ShipQTY',
            'ShipDate',
            'CustomerID',
            'AccountName',
            'Email',
            'AddressLine1',
            'AddressLine2',
            'City',
            'State',
            'Country',
            'Zip',
            'WarehouseID',
            'PackageCount',
            'SOLinePrice',
            'FreightCost',
            'SenttoWH',
            'InsertedDT',
            'LastModifiedDT',
            'Tracking',
            'TrackingCreatedDate',
            'CustomerPhone',
            'Attention',
            'ShipVia',
            'Carrier',
            'CourierCode',
            'CourierName',
            'ConfirmedDateTime',
            'CreatedDatetime',
        ],
    },
    '_util.AfterShipLog': {
        'keys': [
            'ShipmentNbr',
            'OrderNbr',
            'Tracking',
        ],
        'columns': [
            'ShipmentNbr',
            'OrderNbr',
            'Tracking',
            'ResponseCode',
            'Message',
            'ID',
            'Timestamp'
        ],
        'update_columns': [
            'ResponseCode',
            'Message',
            'ID',
            'Timestamp'
        ],
    },
    'hs.deal_snapshots': {
        'keys': [
            'snapshot_at',
            'deal_id',
            'stage',
            'rep_name',
        ],
        'columns': [
            'snapshot_at',
            'deal_id',
            'deal_name',
            'stage',
            'deal_type',
            'rep_name',
            'team',
            'product',
            'amount',
            'lead_source',
            'order_number',
            'is_true_won',
            'is_stalled',
            'create_date',
            'close_date',
            'last_activity_date',
            'days_in_pipeline',
            'days_since_activity',
            'closed_lost_reason',
            'primary_competitor',
        ],
        'update_columns': [
            'deal_name',
            'deal_type',
            'team',
            'product',
            'amount',
            'lead_source',
            'order_number',
            'is_true_won',
            'is_stalled',
            'create_date',
            'close_date',
            'last_activity_date',
            'days_in_pipeline',
            'days_since_activity',
            'closed_lost_reason',
            'primary_competitor',
        ],
    },
    'hs.activity_snapshots': {
        'keys': [
            'snapshot_at',
            'rep_name',
            'window',
            'call_count',
            'email_count',
            'meeting_count',
            'task_count',
            'new_contact_count',
        ],
        'columns': [
            'snapshot_at',
            'rep_name',
            'team',
            'window',
            'call_count',
            'email_count',
            'meeting_count',
            'task_count',
            'new_contact_count',
        ],
        'update_columns': [
            'team',
        ],
    },
}

'''# Tables

Tables is used to drive the SQLConnector's checked_upsert functionality

<hr>

## Structure
 >>> 'table_name': { #replace table_name with the name of the table. We'll use AdDetails
        'keys': [ #replace keys entries with the names of the primary key column(s) in the table
            'primary_key_column_1', 
            'primary_key_column_2'
        ],
        'columns': [ #replace column entries with the names of all columns in the table
            'primary_key_column_1',
            'primary_key_column_2',
            'column_1',
            'column_2',
            'column_3'
        ],
        'update_columns': [ #replace update_columns entries with column names that are NOT keys
            'column_1',
            'column_2',
            'column_3'
        ],
 }
 
 >>> 'AdDetails': {
        'keys': [
            'AdCode',
        ],
        'columns': [
            'AdCode',
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
        'update_columns': [
            'AdVersionID',
            'PrimaryAdName',
            'SecondaryAdName',
            'Category',
            'StartDate',
            'DateCreated',
            'CreatedBy',
            'LastModBy'
        ],
 }
'''



# Database configurations as dictionaries
DATABASES = {
    'db_CentralStore': {
        'server': os.getenv('CENTRALSTORE_SERVER'),
        'database': os.getenv('CENTRALSTORE_DATABASE'),
        'username': os.getenv('CENTRALSTORE_USERNAME'),
        'password': os.getenv('CENTRALSTORE_PASSWORD'),
    },
    'AcumaticaDb': {
        'server': os.getenv('ACUMATICA_SERVER'),
        'database': os.getenv('ACUMATICA_DATABASE'),
        'username': os.getenv('ACUMATICA_USERNAME'),
        'password': os.getenv('ACUMATICA_PASSWORD'),
    }
}

AVS = {
    'account': os.getenv('AVS_ACCOUNT'),
    'license': os.getenv('AVS_LICENSE')
}
RMI = {
    'username': os.getenv('RMI_USERNAME'),
    'password': os.getenv('RMI_PASSWORD')
}

REDSTAG = {
    'username': os.getenv('REDSTAG_USERNAME'),
    'password': os.getenv('REDSTAG_PASSWORD')
}

ACUMATICA_API = {
    'username': os.getenv('ACUMATICA_API_USERNAME'),
    'password': os.getenv('ACUMATICA_API_PASSWORD'),
    'username2': os.getenv('ACUMATICA_API_USERNAME2'),
    'password2': os.getenv('ACUMATICA_API_PASSWORD2'),
    'username3': os.getenv('ACUMATICA_API_USERNAME3'),
    'password3': os.getenv('ACUMATICA_API_PASSWORD3'),
}

CRITEO = {
    'client_id': os.getenv('CRITEO_CLIENT_ID'),
    'client_secret': os.getenv('CRITEO_CLIENT_SECRET'),
    'ad_id': os.getenv('CRITEO_ADVERTISER_ID')
}

KUSTOMER = {
    'webhook': os.getenv('KUSTOMER_WEBHOOK')
}

HUBSPOT = {
    'access_token': os.getenv('HUBSPOT_ACCESS_TOKEN')
}

SHOPIFY = {
    'domain': 'journey-health-lifestyle.myshopify.com',
    'version': "2024-07",
    'token': os.getenv('SHOP_API_TOKEN'),
    'key': os.getenv('SHOP_API_KEY'),
    'secret': os.getenv('SHOP_API_SECRET')
}

TEAMS = {
    'tenant_id':        os.getenv('TEAMS_TENANT_ID'),
    'client_id':        os.getenv('TEAMS_CLIENT_ID'),
    'client_secret':    os.getenv('TEAMS_CLIENT_SECRET'),
    'user_id':          os.getenv('TEAMS_USER_ID'),
    'sp_object_id':     os.getenv('TEAMS_SP_OBJECT_ID'),
    'webhook_url':      os.getenv('TEAMS_WEBHOOK_URL'),
}


AFTERSHIP = {
    'api_key': os.getenv('AFTERSHI_API_KEY')
}
